import sys
import os
import pandas as pd
import numpy as np
from datetime import timedelta
from rich.console import Console
from rich.table import Table

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from backtest.engines.walk_forward import WalkForwardOptimizer

console = Console()

def run_analysis():
    console.print("\n[bold magenta]🔬 Running 10x Critical Trade Analysis...[/]")
    
    # Run WFO to get the raw list of out-of-sample trades
    wfo = WalkForwardOptimizer(symbol="BTCUSDT", interval="15m", train_days=90, test_days=30)
    result = wfo.run()
    
    trades = result.trades
    if not trades:
        console.print("[red]No trades generated by WFO![/]")
        return
        
    df = wfo._load_data()
    
    mfe_list = []
    mae_list = []
    
    tp2_mfes = []
    sl_mfes = []
    be_mfes = []
    
    console.print(f"\n[cyan]Analyzing {len(trades)} trades for MFE/MAE...[/]")
    
    for t in trades:
        # Get data for 48 hours after entry to see what the market actually did
        entry_idx_loc = df.index.get_loc(t.entry_time)
        # Look forward up to 192 candles (48 hours on 15m) or end of df
        end_idx = min(entry_idx_loc + 192, len(df))
        
        # We need the slice *after* entry to calculate excursion
        future_df = df.iloc[entry_idx_loc+1:end_idx]
        
        if len(future_df) == 0:
            continue
            
        max_high = future_df['high'].max()
        min_low = future_df['low'].min()
        
        # Original risk per trade in price terms (1R)
        # We don't have the exact SL price in the trade object easily, 
        # but we know avg loss is ~$200 on $10k, so 1R is 2% of $10k.
        # Let's calculate R based on the entry price and the ATR mult.
        # But wait, we don't have ATR mult in the trade. 
        # Let's approximate 1R based on the trade size. We risk $200 per trade.
        risk_usd = 200.0
        
        # Favorable and Adverse excursions in USD per total position size
        if t.direction == "LONG":
            favorable_usd = (max_high - t.entry_price) * t.size
            adverse_usd = (min_low - t.entry_price) * t.size
        else:
            favorable_usd = (t.entry_price - min_low) * t.size
            adverse_usd = (t.entry_price - max_high) * t.size
            
        mfe_r = favorable_usd / risk_usd
        mae_r = adverse_usd / risk_usd  # This will be negative
        
        mfe_list.append(mfe_r)
        mae_list.append(mae_r)
        
        if t.exit_type == "TAKE_PROFIT_2":
            tp2_mfes.append(mfe_r)
        elif t.exit_type == "STOP_LOSS":
            sl_mfes.append(mfe_r)
        elif t.exit_type == "BREAKEVEN":
            be_mfes.append(mfe_r)
            
    # Print statistics
    console.print("\n[bold yellow]📊 Trade Excursion Analysis (MFE / MAE)[/]")
    console.print("MFE (Max Favorable Excursion) measures how far in profit a trade went before reversing.")
    console.print("Values are in 'R' multiples (1R = Initial Risk of $200).\n")
    
    console.print(f"[green]TAKE_PROFIT_2 Trades ({len(tp2_mfes)} trades):[/]")
    console.print(f"  Avg MFE: +{np.mean(tp2_mfes):.2f}R")
    console.print(f"  Max MFE: +{np.max(tp2_mfes):.2f}R")
    console.print(f"  % that reached ≥ 3.0R: {sum(1 for m in tp2_mfes if m >= 3.0) / len(tp2_mfes) * 100:.1f}%")
    console.print(f"  % that reached ≥ 5.0R: {sum(1 for m in tp2_mfes if m >= 5.0) / len(tp2_mfes) * 100:.1f}%")
    
    if sl_mfes:
        console.print(f"\n[red]STOP_LOSS Trades ({len(sl_mfes)} trades):[/]")
        console.print(f"  Avg MFE before hitting stop: +{np.mean(sl_mfes):.2f}R")
        console.print(f"  % that reached ≥ 0.5R before stopping: {sum(1 for m in sl_mfes if m >= 0.5) / len(sl_mfes) * 100:.1f}%")
        console.print(f"  % that reached ≥ 0.8R before stopping: {sum(1 for m in sl_mfes if m >= 0.8) / len(sl_mfes) * 100:.1f}%")
        
    if be_mfes:
        console.print(f"\n[cyan]BREAKEVEN Trades ({len(be_mfes)} trades):[/]")
        console.print(f"  Avg MFE: +{np.mean(be_mfes):.2f}R")
        console.print(f"  Max MFE: +{np.max(be_mfes):.2f}R")

if __name__ == "__main__":
    run_analysis()
