import sys
import os
import pandas as pd
import numpy as np
from datetime import timedelta
from rich.console import Console

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backtest.engines.walk_forward import WalkForwardOptimizer

console = Console()

def add_adx(df, period=14):
    df = df.copy()
    high = df['high']
    low = df['low']
    close = df['close']

    # TR
    tr1 = high - low
    tr2 = (high - close.shift()).abs()
    tr3 = (low - close.shift()).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

    # Directional Movement
    up_move = high - high.shift()
    down_move = low.shift() - low

    pos_dm = np.where((up_move > down_move) & (up_move > 0), up_move, 0.0)
    neg_dm = np.where((down_move > up_move) & (down_move > 0), down_move, 0.0)

    # Smoothed
    tr_smooth = tr.ewm(alpha=1/period, adjust=False).mean()
    pos_dm_smooth = pd.Series(pos_dm, index=df.index).ewm(alpha=1/period, adjust=False).mean()
    neg_dm_smooth = pd.Series(neg_dm, index=df.index).ewm(alpha=1/period, adjust=False).mean()

    # DI
    di_plus = 100 * (pos_dm_smooth / tr_smooth)
    di_minus = 100 * (neg_dm_smooth / tr_smooth)

    # ADX
    dx = 100 * (abs(di_plus - di_minus) / (di_plus + di_minus).replace(0, 1))
    adx = dx.ewm(alpha=1/period, adjust=False).mean()
    
    df['adx'] = adx
    return df

def run_analysis():
    console.print("\n[bold magenta]🔬 Running Volatility Regime Analyzer...[/]")
    
    # We only need the OOS trades from the WFO
    wfo = WalkForwardOptimizer(symbol="BTCUSDT", interval="15m", train_days=180, test_days=60)
    result = wfo.run()
    
    trades = result.trades
    if not trades:
        console.print("[red]No trades generated by WFO![/]")
        return
        
    df = wfo._load_data()
    df = add_adx(df)
    
    # Calculate rolling percentiles for BB Width and ATR
    df['bb_width_pct'] = df['bb_width'] / df['close'] * 100
    df['atr_pct'] = df['atr'] / df['close'] * 100
    
    df['bb_width_percentile'] = df['bb_width_pct'].rolling(1000).apply(lambda x: pd.Series(x).rank(pct=True).iloc[-1])
    df['atr_percentile'] = df['atr_pct'].rolling(1000).apply(lambda x: pd.Series(x).rank(pct=True).iloc[-1])
    
    # ── Phase 1: Worst Folds Analysis ──
    # Map dates for worst folds
    # Fold 4: Jul 2024
    # Fold 10: Jan 2025
    # Fold 11: Feb 2025
    # Fold 14: May 2025
    # Fold 23: Feb 2026
    # Fold 26: May 2026
    
    worst_months = [(2024, 7), (2025, 1), (2025, 2), (2025, 5), (2026, 2), (2026, 5)]
    worst_trades = [t for t in trades if (t.entry_time.year, t.entry_time.month) in worst_months]
    
    choppy_count = 0
    wicked_count = 0
    vol_spike_count = 0
    
    for t in worst_trades:
        idx = df.index.get_loc(t.entry_time)
        entry_row = df.iloc[idx]
        
        # Choppy market? (ADX < 25)
        if entry_row['adx'] < 25:
            choppy_count += 1
            
        # Volatility spike? (BB width > 80th percentile)
        if entry_row['bb_width_percentile'] > 0.80:
            vol_spike_count += 1
            
        # Wicked out? (MFE > 0.8R before hitting stop)
        end_idx = min(idx + 192, len(df))
        future_df = df.iloc[idx+1:end_idx]
        if len(future_df) > 0:
            max_high = future_df['high'].max()
            if t.direction == "LONG":
                favorable_usd = (max_high - t.entry_price) * t.size
                risk_usd = 200.0 # Approx 1R
                mfe_r = favorable_usd / risk_usd
                if mfe_r >= 0.8 and t.exit_type == "STOP_LOSS":
                    wicked_count += 1
                    
    console.print(f"\n[bold red]── Worst Folds Analysis ({len(worst_trades)} losing trades) ──[/]")
    console.print(f"C. Market Choppy (ADX < 25)        : {choppy_count} trades ({choppy_count/len(worst_trades)*100:.1f}%)")
    console.print(f"B. Stop Too Tight (MFE > 0.8R)     : {wicked_count} trades ({wicked_count/len(worst_trades)*100:.1f}%)")
    console.print(f"D. Volatility Spike (BB Width >80%): {vol_spike_count} trades ({vol_spike_count/len(worst_trades)*100:.1f}%)")
    
    # ── Phase 2: Profit Factor by Regime ──
    console.print("\n[bold cyan]── Phase 2: Profit Factor by Regime (All Trades) ──[/]")
    
    def calc_pf(trades_subset):
        if not trades_subset: return 0.0
        gross_profit = sum(t.pnl for t in trades_subset if t.pnl > 0)
        gross_loss = abs(sum(t.pnl for t in trades_subset if t.pnl < 0))
        return gross_profit / gross_loss if gross_loss > 0 else 999.0
        
    def get_row(t):
        return df.iloc[df.index.get_loc(t.entry_time)]
        
    # By ADX
    adx_bins = [(0, 20), (20, 25), (25, 30), (30, 100)]
    console.print("\n[bold]PF by ADX (Trend Strength)[/]")
    for lower, upper in adx_bins:
        subset = [t for t in trades if lower <= get_row(t)['adx'] < upper]
        pf = calc_pf(subset)
        console.print(f"ADX {lower}-{upper}: PF = {pf:.2f} ({len(subset)} trades)")
        
    # By BB Width Percentile
    bb_bins = [(0, 0.33, "Low Vol"), (0.33, 0.66, "Mid Vol"), (0.66, 1.0, "High Vol")]
    console.print("\n[bold]PF by BB Width (Volatility Regime)[/]")
    for lower, upper, name in bb_bins:
        subset = [t for t in trades if lower <= get_row(t)['bb_width_percentile'] < upper]
        pf = calc_pf(subset)
        console.print(f"{name} ({lower*100:.0f}-{upper*100:.0f}%): PF = {pf:.2f} ({len(subset)} trades)")
        
    # By ATR Percentile
    console.print("\n[bold]PF by ATR Percentile (True Range Regime)[/]")
    for lower, upper, name in bb_bins:
        subset = [t for t in trades if lower <= get_row(t)['atr_percentile'] < upper]
        pf = calc_pf(subset)
        console.print(f"{name} ({lower*100:.0f}-{upper*100:.0f}%): PF = {pf:.2f} ({len(subset)} trades)")

if __name__ == "__main__":
    run_analysis()
